package flandre.scarlet.thevoidkingdom.functions.enchant;

import flandre.scarlet.thevoidkingdom.utils.game.menu.MenuIcon;
import org.bukkit.Material;

import java.util.List;

public class EnchantMenuIcon {
    public static final MenuIcon CLOSE = MenuIcon.create(Material.SHEARS, 4950136, 1, "<!italic><bold><red>停止思索", List.of("<!italic><yellow>%img_line%", "<!italic><gray>  你对目前的思索成果不满意", "<!italic><gray>  点击放弃所有思索成果并退出", "<!italic><gray>  附魔台上的物品无任何变化", "<!italic><gray>  附魔耗材和经验不会返还", "<!italic><yellow>%img_line%"));
    public static final MenuIcon FINISH = MenuIcon.create(Material.SHEARS, 4950136, 1, "<!italic><bold><green>完成思索", List.of("<!italic><yellow>%img_line%", "<!italic><gray>  你对目前的思索成果已满意", "<!italic><gray>  点击总结你的思索成果", "<!italic><gray>  附魔台上的物品将被附魔", "<!italic><yellow>%img_line%"));
    public static final MenuIcon CARD = MenuIcon.create(Material.SHEARS, 4950158, 1, "<!italic><bold><aqua>未知卡牌", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  点击进行思索", "<!italic><gray>  消耗 <green>1 <gray>思绪点", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon ATTACK_DAMAGE_WARRIOR = MenuIcon.create(Material.SHEARS, 4950159, 1, "<!italic><bold><aqua>魔咒: 锋利", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高锋利附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高近战武器的基础伤害", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon ATTACK_DAMAGE_ARCHER = MenuIcon.create(Material.SHEARS, 4950160, 1, "<!italic><bold><aqua>魔咒: 利箭", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高利箭附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高射箭武器的基础伤害", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon ATTACK_DAMAGE_MAGE = MenuIcon.create(Material.SHEARS, 4950161, 1, "<!italic><bold><aqua>魔咒: 咒术", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高咒术附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高魔法武器的基础伤害", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon CRITICAL_STRIKE_POWER = MenuIcon.create(Material.SHEARS, 4950162, 1, "<!italic><bold><aqua>魔咒: 会心", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高会心附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高暴击伤害", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon CRITICAL_STRIKE_CHANCE = MenuIcon.create(Material.SHEARS, 4950163, 1, "<!italic><bold><aqua>魔咒: 幸运", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高幸运附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高暴击概率", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MAX_DURABILITY = MenuIcon.create(Material.SHEARS, 4950164, 1, "<!italic><bold><aqua>魔咒: 耐久", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高耐久附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高耐久度上限", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon DEFENSE = MenuIcon.create(Material.SHEARS, 4950165, 1, "<!italic><bold><aqua>魔咒: 抵挡", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高抵挡附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高基础防御", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MANA_REGENERATION = MenuIcon.create(Material.SHEARS, 4950166, 1, "<!italic><bold><aqua>魔咒: 魔涌", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高魔涌附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高魔力回复", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon HEALTH_REGENERATION = MenuIcon.create(Material.SHEARS, 4950167, 1, "<!italic><bold><aqua>魔咒: 回天", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高回天附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高生命回复", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon SKILL_DAMAGE = MenuIcon.create(Material.SHEARS, 4950168, 1, "<!italic><bold><aqua>魔咒: 灵击", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高灵击附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高符卡伤害", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon BLUNT_POWER = MenuIcon.create(Material.SHEARS, 4950176, 1, "<!italic><bold><aqua>魔咒: 巨大", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高巨大附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高战锤的锤击范围", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon BLUNT_RATING = MenuIcon.create(Material.SHEARS, 4950177, 1, "<!italic><bold><aqua>魔咒: 沉重", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高沉重附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高战锤的锤伤比例", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon BLOCK_POWER = MenuIcon.create(Material.SHEARS, 4950178, 1, "<!italic><bold><aqua>魔咒: 铁壁", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高铁壁附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高盾的格挡比例", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon BLOCK_RATING = MenuIcon.create(Material.SHEARS, 4950179, 1, "<!italic><bold><aqua>魔咒: 牢靠", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高牢靠附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高盾的格挡概率", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon KNOCKBACK = MenuIcon.create(Material.SHEARS, 4950180, 1, "<!italic><bold><aqua>魔咒: 击退", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高击退附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高长剑的击退能力", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon FIRE_ASPECT = MenuIcon.create(Material.SHEARS, 4950181, 1, "<!italic><bold><aqua>魔咒: 烈刃", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高烈刃附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高长剑的点燃时间", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon ARROW_VELOCITY = MenuIcon.create(Material.SHEARS, 4950182, 1, "<!italic><bold><aqua>魔咒: 流矢", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高流矢附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高射箭武器的箭矢速度", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon ARROW_FIRE = MenuIcon.create(Material.SHEARS, 4950183, 1, "<!italic><bold><aqua>魔咒: 火矢", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高火矢附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高弓的箭矢点燃时间", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon PIERCING = MenuIcon.create(Material.SHEARS, 4950184, 1, "<!italic><bold><aqua>魔咒: 穿透", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高穿透附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高弩的箭矢穿透能力", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon MANA_COST = MenuIcon.create(Material.SHEARS, 4950185, 1, "<!italic><bold><aqua>魔咒: 节约", List.of("<!italic><yellow>%img_short_line_1%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高节约附魔的等级", "<!italic><yellow>%img_short_line_1%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  降低魔法武器的魔力消耗", "<!italic><yellow>%img_short_line_1%"));
    public static final MenuIcon DODGE_RATING = MenuIcon.create(Material.SHEARS, 4950186, 1, "<!italic><bold><aqua>魔咒: 灵活", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高灵活附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高闪避概率", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MAX_MANA = MenuIcon.create(Material.SHEARS, 4950187, 1, "<!italic><bold><aqua>魔咒: 充沛", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高充沛附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高魔力上限", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MAX_HEALTH = MenuIcon.create(Material.SHEARS, 4950188, 1, "<!italic><bold><aqua>魔咒: 底力", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高底力附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高生命上限", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon PHYSICAL_DAMAGE_REDUCTION = MenuIcon.create(Material.SHEARS, 4950189, 1, "<!italic><bold><aqua>魔咒: 坚韧", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高坚韧附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高物理抗性", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MAGIC_DAMAGE_REDUCTION = MenuIcon.create(Material.SHEARS, 4950190, 1, "<!italic><bold><aqua>魔咒: 咒御", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  提高咒御附魔的等级", "<!italic><yellow>%img_short_line_3%", "<!italic><gold> %img_info% 魔咒效果:", "<!italic><gray>  提高魔法抗性", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon REALLOC = MenuIcon.create(Material.SHEARS, 4950169, 1, "<!italic><bold><gold>新的开始", List.of("<!italic><yellow>%img_line%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  在思绪点不变的情况下洗牌", "<!italic><gray>  即刷新所有卡牌", "<!italic><yellow>%img_line%"));
    public static final MenuIcon STOP = MenuIcon.create(Material.SHEARS, 4950170, 1, "<!italic><bold><red>精神涣散", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  翻开任意一张时触发", "<!italic><gray>  清空所有思绪点", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MORE_POINT_1 = MenuIcon.create(Material.SHEARS, 4950171, 1, "<!italic><bold><gold>灵光一闪", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  获得额外 <green>3 <gray>思绪点", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MORE_POINT_2 = MenuIcon.create(Material.SHEARS, 4950172, 1, "<!italic><bold><gold>茅塞顿开", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  获得额外 <green>5 <gray>思绪点", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon MORE_POINT_3 = MenuIcon.create(Material.SHEARS, 4950173, 1, "<!italic><bold><gold>醍醐灌顶", List.of("<!italic><yellow>%img_short_line_3%", "<!italic><gray>  连续翻开两张时触发", "<!italic><gray>  获得额外 <green>8 <gray>思绪点", "<!italic><yellow>%img_short_line_3%"));
    public static final MenuIcon POINT = MenuIcon.create(Material.SHEARS, 4950174, 1, "<!italic><bold><green>思绪点", null);
    public static final MenuIcon NO_POINT = MenuIcon.create(Material.SHEARS, 4950175, 1, "<!italic><bold><red>灵感枯竭", List.of("<!italic><yellow>%img_short_line_2%", "<!italic><gray>  对于继续进行附魔", "<!italic><gray>  你现在没有任何头绪", "<!italic><gray>  是时候结束这次附魔了", "<!italic><yellow>%img_short_line_2%"));
}
